config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  root 'static#home'
  devise_for :users,
  path: '',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  get 'about', to: 'static#about'

  resources :posts

  resources :tags, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_one :user, through: :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts

  has_many :users, through: :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, through: :posts

  has_many :tags, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_url])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  # before_action :authenticate_user!, only: [:new, :edit]
  # before_action :authenticate_user!, except: [:new, :edit]

  def index
    news_url = 'https://newsapi.org/v1/articles?source=national-geographic&sortBy=top&apiKey=ba8b42abfab743f3bfe37fe0f9df3557'
    response = HTTParty.get(news_url)
    @news_data = response

    @all_posts = current_user.posts
    # @new_post = Post.new  #post is not tagged to user
    @new_post = current_user.posts.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    render html: 'show form to create new post'
  end

  def edit
    @edit_post = Post.find(params[:id])
  end

  def create
    creating_post = post_params
    # render json: params[:post]

  Post.create(creating_post)
    redirect_to posts_path

  end

  def destroy
    Post.destroy(params[:id])

    # deleted_post = Post.find(params[:id])
    # deleted_post.destroy
    redirect_to posts_path
  end

  def update
    updated_post = Post.find(params[:id])

    updated_post.update(post_update_params)

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  def post_update_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    # render json: params
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @all_tags = Tag.all
    render json: @all_tags
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    "Title"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggiesPsql</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
<div class="container">

    <h1>Title is:
      <%= yield(:title) %></h1>
      <%= render "partials/nav" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer>
      &copy; Bloggies 2017
    </footer>
  </div>

  </body>
</html>

app/views/partials/_nav.html.erb
<nav>
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Posts", posts_path %>

    </li>

<% if current_user %>
  <!-- true -->
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>

<% else %>
  <!-- false -->
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Register", new_user_registration_path %>
<% end %>

</ul>
</nav>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post: #{@edit_post.id}") %>

<small>inspect: <%= @edit_post.inspect %></small>

<%= form_for @edit_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

    <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, "Bloggies || Current user #{current_user.name}") %>

<h1>All posts by
  <%= current_user.name %></h1>

<% @news_data["articles"].each do |article| %>
<ul>
  <li>
    <h3><%= article["title"] %></h3>
    <%= image_tag article["urlToImage"], width: 600 %>
    <h4><%= article["description"] %></h4>
    <a href="<%= article[" url"] %>">Read more...</a>
  </li>
</ul>
<% end %>

<h1>Create a post</h1>

<%= form_for @new_post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :content %>
<%= f.text_field :content %>

<%= f.hidden_field :user_id %>

<%= f.submit %>
<% end %>

<%#= @new_post.inspect %>

<% @all_posts.each_with_index do |post, index| %>
<% if post.id %>
<h3>
<li>
  <%= post.title %>
</li>
</h3>

<p>
<%= post.content %>
</p>
<%= link_to "View", post_path(post) %>
<%= link_to "Delete", post_path(post), method: :delete %>
<%= link_to "Edit", edit_post_path(post)%>

<% end %>
<% end %>

<div class=""></div>

app/views/posts/show.html.erb
<% provide(:title, "#{@post.title}") %>

<h1><%= @post.title %></h1>
<small>
  Author: <%= @post.user.name %> (<%= @post.created_at %>)
</small>
<p>
  <%= @post.content %>
</p>

<%= link_to "My posts", posts_path %>